// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seguros.Api.Persistencia;

namespace Seguros.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220529015704_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Seguros.Api.Modelos.Asegurados", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cedula")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("edad")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Asegurados");
                });

            modelBuilder.Entity("Seguros.Api.Modelos.AseguradosSeguros", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("aseguradosId")
                        .HasColumnType("int");

                    b.Property<int>("segurosId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("aseguradosId");

                    b.HasIndex("segurosId");

                    b.ToTable("AseguradosSeguros");
                });

            modelBuilder.Entity("Seguros.Api.Modelos.Seguros", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prima")
                        .HasColumnType("float");

                    b.Property<double>("suma_asegurada")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Seguros");
                });

            modelBuilder.Entity("Seguros.Api.Modelos.AseguradosSeguros", b =>
                {
                    b.HasOne("Seguros.Api.Modelos.Asegurados", "asegurados")
                        .WithMany()
                        .HasForeignKey("aseguradosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Seguros.Api.Modelos.Seguros", "seguros")
                        .WithMany()
                        .HasForeignKey("segurosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
